### ISSUE TITLE
fix opening non-existent sub directories in URL  

### ISSUE THREAD

**Issue by sinaamini92** [red-gold/ts-ui#41]
**Describe the bug**
entering a random subdirectory after the main URL, opens a profile that doesn't exist

**To Reproduce**
1. Go to browser's address bar
2. enter random string after the URL [eg: "social.telar.dev/yahoo.com"]
3. shows a non-existent profile

**Expected behavior**
to show 404

**Screenshots**
![Screenshot from 2021-05-17 05-27-09](https://user-images.githubusercontent.com/28287280/118419174-8d990280-b6d0-11eb-8f5a-640ba04ce33a.jpg)

**Desktop:**
 - OS: Ubuntu 20.04 LTS
 - Browser: chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by Qolzam** [comment]
Dear @sinaamini92 ,

The issue is fixed. Please help me to retest!

Thanks 😊

**Comment by sinaamini92** [comment]
@Qolzam it still shows the non-existent route as a profile for a few seconds then redirects to the 404 page

**Comment by Qolzam** [comment]
Thank you for checking 🙂 the issue is fixed. Please help me to retest.

**Comment by sinaamini92** [comment]
that seems to be fixed thanks
